### PR TITLE
SET-769 CCI having broken EAP6.4 jobs

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/SET-769

### CODE REVIEW

**Comment by RanabirChakraborty** [comment]
@iweiss @spyrkob please review.

**Comment by iweiss** [comment]
Why not use `mvn_home_folder`?

**Comment by RanabirChakraborty** [comment]
maven 3.2.5 needs to be installed inside the mentioned path https://github.com/jbossas/jboss-eap/blob/6.4.x/integration-tests.sh#L26-L30 and mvn_home_folder is `/opt/apache`

**Comment by spyrkob** [comment]
>maven 3.2.5 needs to be installed inside the mentioned path https://github.com/jbossas/jboss-eap/blob/6.4.x/integration-tests.sh#L26-L30 and mvn_home_folder is /opt/apache

This is used for a local path search in the eap checkout not a global path see https://github.com/jbossas/jboss-eap/blob/6.4.x/integration-tests.sh#L137 . 3.2.5 should be installed in `/opt/apache` like other versions

**Pull request closed without merging**
