### PR TITLE
add Gitlab configurations and update pr-processor default version to …

### PR DESCRIPTION
**Pull request by soul2zimate**
…0.8.9.Final

working with the gitlab change for adding gitlab configuration to olympus branch.

cc: @rpelisse  @spyrkob

### CODE REVIEW

**Review by spyrkob — APPROVED** [review]
Does the default pr_processor version in zeus_vars/jobs.yml need to be updated as well? 

Probably should try to extract both definitions into one place, but that can be a separate PR. LGTM otherwise

**Comment by soul2zimate** [comment]
yep, I have added the change for jobs.yml in merge request as well. thanks.

**Comment by rpelisse** [comment]
> Does the default pr_processor version in zeus_vars/jobs.yml need to be updated as well?
> 
> Probably should try to extract both definitions into one place, but that can be a separate PR. LGTM otherwise

That's actually kind of bug. We need to have this information live only one place. I'll try to fix that up.

**Comment by soul2zimate** [comment]
Can this get merged ? along with https://gitlab.cee.redhat.com/jboss-set/zeus-vars/-/merge_requests/6

**Comment by spyrkob** [comment]
Created https://github.com/jboss-set/zeus/issues/82 to track the pr_processor version work.

**Pull request merged**
