### PR TITLE
[SET-267] Clean up Mjolnir related tasks and configuration

### PR DESCRIPTION
**Pull request by rpelisse**

### CODE REVIEW

**Comment by rpelisse** [comment]
@spyrkob I was thinking of doing that manually, rather than doing it with Ansible. WDTK?

**Comment by spyrkob** [comment]
You still need to remove them from ansible definition otherwise they'll get recreated right?

**Comment by rpelisse** [comment]
Ah yes, you are right, but this will break EAP7. I wanted to do first the cleaning that does not required to restart EAP7. So that we can have a clean "ansible state". Then we need to schedule a restart for EAP7 and remove the current config (plus cleaned up the module)

**Comment by spyrkob** [comment]
OK makes sense :)

**Pull request merged**
