### PR TITLE
SET-472 java role - molecule refactor into Molecule testsuite

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/SET-472

### CODE REVIEW

**Comment by rpelisse** [comment]
@RanabirChakraborty I think we can do better here. Instead of creating dummy files I would suggest you download openjdk and actually install them. Fetch two different version and test that both are functionnal in the verify.yml.

**Review by rpelisse — CHANGES_REQUESTED** [review]
See comment above.

**Comment by RanabirChakraborty** [comment]
@rpelisse I have just used only jdk-17.0.1 (I guess it'll serve the testing of the java role). Otherwise downloading two different versions, installing and checking them will take a long time to execute Github CI.

**Review by rpelisse — CHANGES_REQUESTED** [review]
@RanabirChakraborty please! Don't add binary files to the projet! Use get_url: to retrieve them from the internet.

**Pull request merged**
