### PR TITLE
SET-465 Zeus - Refactor current CI into a proper Molecule testsuite.

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/SET-465

### CODE REVIEW

**Comment by RanabirChakraborty** [comment]
Handled "motd" and "java" role.

**Comment by rpelisse** [comment]
@RanabirChakraborty I've tested it, it works pretty good, but can your refactor the directory layout to be molecule/default instead of molecule/molecule/default? 

Thanks!

**Comment by RanabirChakraborty** [comment]
@rpelisse I have tried to change the path from `molecule/molecule/default` to `molecule/default` but it's showing me the below error. Not sure if I'm missing something or it has to be like this only.
```
[rchakrab@rchakrab:~/Work/zeus]$ molecule test
INFO     default scenario test matrix: dependency, lint, cleanup, destroy, syntax, create, prepare, converge, idempotence, side_effect, verify, cleanup, destroy
INFO     Performing prerun...
INFO     Running ansible-galaxy role install -vr requirements.yml --roles-path /home/rchakrab/.cache/ansible-compat/e8022f/roles
WARNING  Retrying execution failure 1 of: ansible-galaxy role install -vr requirements.yml --roles-path /home/rchakrab/.cache/ansible-compat/e8022f/roles
ERROR    [0;34mUsing /etc/ansible/ansible.cfg as config file[0m
```
(I have changed the path from molecule/molecule/default to testsuite/molecule/default)

**Comment by RanabirChakraborty** [comment]
@rpelisse I have tried to change the path from `molecule/molecule/default` to `molecule/default` but it's showing me the below error. Not sure if I'm missing something or it has to be like this only.
```
[rchakrab@rchakrab:~/Work/zeus]$ molecule test
INFO     default scenario test matrix: dependency, lint, cleanup, destroy, syntax, create, prepare, converge, idempotence, side_effect, verify, cleanup, destroy
INFO     Performing prerun...
INFO     Running ansible-galaxy role install -vr requirements.yml --roles-path /home/rchakrab/.cache/ansible-compat/e8022f/roles
WARNING  Retrying execution failure 1 of: ansible-galaxy role install -vr requirements.yml --roles-path /home/rchakrab/.cache/ansible-compat/e8022f/roles
ERROR    [0;34mUsing /etc/ansible/ansible.cfg as config file[0m
```
(I have changed the path from molecule/molecule/default to testsuite/molecule/default)

**Comment by rpelisse** [comment]
Yep, that because of the qualys role in the requirement file. i would suggest you move the collection part of this file into molecule/default/requirements.yml and adapt the molecule.yml to load this file instead of the one at the root of the project,, without the qualys role.
Simply set the requirements like [that](https://github.com/ansible-middleware/wildfly/blob/main/molecule/default/molecule.yml#L5):.

**Comment by rpelisse** [comment]
Superseeded by [PR157](https://github.com/jboss-set/zeus/pull/157)

**Pull request closed without merging**
