### PR TITLE
Provide SMTP host and port in separate variables

### PR DESCRIPTION
**Pull request by TomasHofman**
This shell script is probably not yet used by anything except component alignment, so nothing should break.

Cc @spyrkob @rpelisse

### CODE REVIEW

**Comment by rpelisse** [comment]
LGTM

**Comment by spyrkob** [comment]
@TomasHofman is there a PR to change upgrade-components-report.sh ?

**Comment by TomasHofman** [comment]
@spyrkob I'm still working on that one, but the alignment jobs are not yet functional, so you can disregard them for now.

**Comment by TomasHofman** [comment]
Added fix: remove extra space from template file

**Pull request merged**
