### PR TITLE
Deploy internal server certificate to allow Jenkins job to access unverified HTTPS endpoints

### PR DESCRIPTION
**Pull request by rpelisse**
https://projects.engineering.redhat.com/browse/SET-125

@spyrkob can you take a look, see if you like the approach?

### CODE REVIEW

**Comment by spyrkob** [comment]
LGTM

My only nitpick is the cacert password - I think that should be part of jdk variable. Also probably we should change it from the default one ;)

**Comment by rpelisse** [comment]
@spyrkob I'm not a big fan of chaning this password. First, some test can rely on it (for instance to deploy a certifcate for instance) and may break if we change it. Then it adds another secret to manage. Also, those are *test* JVMs. They are not running production software that would need to be secure. They are hidden, inside the CI server. So, IMHO, I would spare us the management of yet an other password, until a concrete need arise :)

**Comment by spyrkob** [comment]
That's fair enough. Still get my system engineer hat on when I see puppet/ansible code ;)

**Comment by rpelisse** [comment]
@spyrkob BTW, I will merge end of next week, as I will also do some tweaking following up SET-125.

**Pull request merged**
