### PR TITLE
nginx: Refactors roles to use vars/ instead of defaults/ for internal…

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/SET-460

### CODE REVIEW

**Comment by rpelisse** [comment]
@RanabirChakraborty I think this PR needs to be rebased ;) !

**Comment by RanabirChakraborty** [comment]
checked the error `Skipping Galaxy server https://galaxy.ansible.com/api/` and seems like Galaxy API appears to be down and that's why the test cases are failing.

**Comment by rpelisse** [comment]
@RanabirChakraborty Yep, I saw that too and I was planning to ignore it. As long as it works on Olympus, I don't mind Molecule failing ;)

**Comment by rpelisse** [comment]
@RanabirChakraborty need a rebase ;)

**Comment by RanabirChakraborty** [comment]
Thanks! Done

**Pull request merged**
