### PR TITLE
SET-503 Tuned role - molecule refactor into Molecule testsuite.

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/SET-503

### CODE REVIEW

**Comment by RanabirChakraborty** [comment]
@rpelisse for rhel8, molecule is not able to install `tuned` package. Here we are using the `fast_yum_install` role internally but I have also tried to do the same via `yum` in prepare.yml but that also is not working. showing me the below error.

```
fatal: [rhel8]: FAILED! => {"changed": false, "failures": ["No package tuned available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
```

Am I missing something here?

**Comment by rpelisse** [comment]
@RanabirChakraborty this can't be merged if the build is failing...

**Comment by RanabirChakraborty** [comment]
Checked but still facing the same issue, role `fast_yum_install` can't able to install `tuned`, need to check again. Till then please keep it on hold

**Comment by rpelisse** [comment]
@RanabirChakraborty Are you still stuck on this PR? I would like to merge it, but C needs to pass first.

**Comment by RanabirChakraborty** [comment]
@rpelisse I have tried a lot but seems like molecule is not able to install the `tuned` package and that's the reason why this test case is failing. If you can check this one, that'll be great.

**Pull request closed without merging**
