### PR TITLE
cci_worker: Refactors roles to use vars/ instead of defaults/ for int…

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/SET-460

### CODE REVIEW

**Comment by RanabirChakraborty** [comment]
@spyrkob I can see you have created `defaults` yesterday. I have tried to look for `override_cci_account_pubkey_file` in zeus-vars but can't able to see it there. I have changed the name to `cci_worker_pubkey_file`.

**Comment by rpelisse** [comment]
@spyrkob I need your ack+ to merge that ;)

**Review by spyrkob — APPROVED** [review]
LGTM. I'll add `cci_worker_pubkey_file` to vars, looks like it slipped through

**Review by rpelisse — CHANGES_REQUESTED** [review]
@RanabirChakraborty can you add the missing vars as mentioned by @spyrkob ? Thanks!

**Comment by spyrkob** [comment]
scratch that, `cci_worker_pubkey_file` doesn't need to be in vars, it should just use the default value

**Review by rpelisse — APPROVED** [review]

**Pull request merged**
