### PR TITLE
SET-446 Mount init scripts as a volume to postgres containers

### PR DESCRIPTION
**Pull request by TomasHofman**
https://issues.redhat.com/browse/SET-446

The SQL init files are mounted under the `/docker-entrypoint-initdb.d` directory, from where they are executed automatically by the postgres container.

### CODE REVIEW

**Comment by rpelisse** [comment]
@TomasHofman it looks good, but we don't need to rename "script" to volume_home. Currently the SQL scripts lives in /opt/tools/pgsql/ and we will just add the volume to wherever the image needs them to be:

```
-v /opt/tools/pgsql/scripts.sql:/wherever/the/image/wants/it:ro
```

**Review by rpelisse — CHANGES_REQUESTED** [review]
See my previous comment about keeping script_home.

**Comment by TomasHofman** [comment]
@rpelisse I updated the PR.

**Comment by rpelisse** [comment]
Awesome! I'm going to test before merging. After it ran successfully on Olympus, I'll restart the component DB and we'll see if this works :)

**Pull request merged**
