### PR TITLE
[SET-557] Enable podman.socket in user scope

### PR DESCRIPTION
**Pull request by spyrkob**

### CODE REVIEW

**Comment by spyrkob** [comment]
@RanabirChakraborty I think that's missing part for SET-570

**Comment by RanabirChakraborty** [comment]
Hopefully, It'll work this time. (fingers crossed)

**Review by RanabirChakraborty — APPROVED** [review]
LGTM @spyrkob Thanks a lot!

**Review by rpelisse — APPROVED** [review]
LGTM

**Pull request merged**
