### PR TITLE
SET-432 Enable ssh access to jenkins user using password auth.

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/SET-432
vars file PR - https://gitlab.cee.redhat.com/jboss-set/zeus-vars/-/merge_requests/42

### CODE REVIEW

**Comment by spyrkob** [comment]
Can't we reuse the sshd role?
I don't like the idea of having the sshd_config duplicated. It seems everything in the sshd role, apart from generating and linking SSH key, should be applicable to the CCI VM.  @rpelisse what is that key used for? Could we move those two steps to another role or break them away into a new one?

**Comment by RanabirChakraborty** [comment]
generating a public key and copying it inside the server's `authorized_keys` file is used for key-based authentication.
But for jenkins we are trying to achieve password-based authentication. For which only editing the `sshd_config` file and restarting sshd will do the work. That's why I haven't used the sshd role.

**Comment by rpelisse** [comment]
@spyrkob @RanabirChakraborty are we sure we need password authentification? Deploying key would be far more secure.

**Comment by spyrkob** [comment]
At the moment Jenkins is configured to use password based auth. We can try changing that later, at the moment I'd rather stick with what's already working.
Either way - the root account in the VM already has the ssh key provisioned for root so those two steps fail (or rather the last one - linking the pub key - fails). If we can get those out of sshd role, or running depending on variable/host, we can reuse the role rather than copy/pasting it into cci_sshd.

**Comment by RanabirChakraborty** [comment]
@spyrkob changed the `sshd` role according to the requirement and now we can able to reuse the role for password-base authentication too.

**Pull request closed without merging**
